# Generated by Django 4.0.1 on 2023-02-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TvDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('remote_status', models.CharField(default='offline', max_length=100)),
                ('remote_status_updated', models.DateTimeField()),
                ('remote_last_image_url', models.CharField(blank=True, max_length=100, null=True)),
                ('remote_last_image_updated', models.DateTimeField()),
                ('is_socket_connected', models.BooleanField(default=False)),
                ('socket_status_updated', models.DateTimeField()),
            ],
        ),
    ]
