# Generated by Django 4.0.1 on 2023-02-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvdevice',
            name='remote_last_image_updated',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='tvdevice',
            name='remote_status_updated',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='tvdevice',
            name='socket_status_updated',
            field=models.DateTimeField(blank=True),
        ),
    ]
