# Generated by Django 4.0.1 on 2023-02-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_tvdevice_remote_last_image_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvdevice',
            name='remote_last_image_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tvdevice',
            name='remote_status_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tvdevice',
            name='socket_status_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
