# Generated by Django 4.0.1 on 2023-02-13 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_tvdevice_remote_last_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvdevice',
            old_name='remote_last_image_url',
            new_name='remote_last_image',
        ),
    ]
