# Generated by Django 4.0.1 on 2023-02-13 12:13

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_rename_remote_last_image_url_tvdevice_remote_last_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvdevice',
            name='remote_last_image',
            field=models.ImageField(upload_to=chat.models.image_path),
        ),
    ]
