# Generated by Django 4.0.1 on 2023-02-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_tvdevice_remote_last_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvdevice',
            name='hdmi_status',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
