# Generated by Django 4.0.1 on 2023-02-14 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_tvdevice_hdmi_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvdevice',
            old_name='hdmi_status',
            new_name='cec_hdmi_status',
        ),
    ]
