# Generated by Django 4.0.1 on 2023-02-14 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_rename_hdmi_status_tvdevice_cec_hdmi_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvdevice',
            name='is_socket_connected',
        ),
    ]
